### PR TITLE
Code review sophia

### PR DESCRIPTION
**Pull request by pchampin**
This is an attempt at improving the Sophia implementation in HdtGraph (and also the implementation of Hdt).

The general idea is to use Arc<str> instead of MownStr, because Arc<str> can be cloned without actually copying the underlying text, and do not require a persistent "owner" of the text.

The performance gain is not obvious, because what takes most time is `FourSectDict::id_to_string`, i.e. the reconstruction of the string from the compressed dictionary. But it still seems that by using Arc<str> we spend less allocating memory than when using MownStr.

This PR also contains a number of minor improvements in the use of the Sophia API.

### CODE REVIEW

**Comment by KonradHoeffner** [comment]
# Benchmarks
## before

```
S??/1.1 (vincent, ?, ?) triple IDs
                        time:   [1.4519 µs 1.4540 µs 1.4545 µs]
S??/1.2 (vincent, ?, ?) str triples
                        time:   [3.2166 µs 3.2189 µs 3.2279 µs]
S??/1.3 (vincent, ?, ?) Sophia triples
                        time:   [4.4290 µs 4.4295 µs 4.4318 µs]

?P? 1429618 triples/2.1 (?, type, ?) triple IDs
                        time:   [342.98 ms 343.09 ms 343.53 ms]
?P? 1429618 triples/2.2 (?, type, ?) str triples
                        time:   [615.83 ms 617.06 ms 621.95 ms]
?P? 1429618 triples/2.3 (?, type, ?) Sophia triples
                        time:   [640.64 ms 640.78 ms 641.37 ms]

??O 1414214 triples/3.1 (?, ?, person) triple IDs
                        time:   [137.56 ms 137.71 ms 138.31 ms]
??O 1414214 triples/3.2 (?, ?, person) str triples
                        time:   [460.17 ms 460.19 ms 460.27 ms]
??O 1414214 triples/3.3 (?, ?, person) Sophia triples
                        time:   [496.97 ms 501.27 ms 502.35 ms]

?PO 1414214 triples/4.1 (?, type, person) triple IDs
                        time:   [117.41 ms 117.91 ms 118.04 ms]
?PO 1414214 triples/4.2 (?, type, person) str subjects
                        time:   [309.76 ms 310.24 ms 312.17 ms]
?PO 1414214 triples/4.3 (?, type, person) str triples
                        time:   [323.12 ms 323.46 ms 323.54 ms]
?PO 1414214 triples/4.4 (?, type, person) Sophia triples
                        time:   [357.56 ms 362.37 ms 363.57 ms]
```

## after

```
S??/1.1 (vincent, ?, ?) triple IDs
                        time:   [1.5132 µs 1.5139 µs 1.5168 µs]
                        change: [+4.0380% +4.2510% +4.4643%] (p = 0.10 > 0.05)
                        No change in performance detected.
S??/1.2 (vincent, ?, ?) str triples
                        time:   [6.2276 µs 6.2297 µs 6.2381 µs]
                        change: [+92.933% +93.432% +93.933%] (p = 0.10 > 0.05)
                        No change in performance detected.
S??/1.3 (vincent, ?, ?) Sophia triples
                        time:   [4.2669 µs 4.2670 µs 4.2670 µs]
                        change: [-3.7215% -3.6888% -3.6561%] (p = 0.07 > 0.05)
                        No change in performance detected.

?P? 1429618 triples/2.1 (?, type, ?) triple IDs
                        time:   [353.45 ms 353.56 ms 354.02 ms]
                        change: [+2.8878% +3.0539% +3.2204%] (p = 0.10 > 0.05)
                        No change in performance detected.
?P? 1429618 triples/2.2 (?, type, ?) str triples
                        time:   [654.45 ms 655.41 ms 659.26 ms]
                        change: [+5.2251% +6.1342% +7.0522%] (p = 0.10 > 0.05)
                        No change in performance detected.
?P? 1429618 triples/2.3 (?, type, ?) Sophia triples
                        time:   [715.80 ms 722.22 ms 723.83 ms]
                        change: [+11.603% +12.294% +12.986%] (p = 0.09 > 0.05)
                        No change in performance detected.

??O 1414214 triples/3.1 (?, ?, person) triple IDs
                        time:   [140.20 ms 140.24 ms 140.40 ms]
                        change: [+1.3715% +1.7188% +2.0680%] (p = 0.09 > 0.05)
                        No change in performance detected.
??O 1414214 triples/3.2 (?, ?, person) str triples
                        time:   [498.61 ms 498.84 ms 499.76 ms]
                        change: [+8.3285% +8.4660% +8.6034%] (p = 0.10 > 0.05)
                        No change in performance detected.
??O 1414214 triples/3.3 (?, ?, person) Sophia triples
                        time:   [552.20 ms 552.79 ms 552.93 ms]
                        change: [+9.9235% +10.589% +11.261%] (p = 0.10 > 0.05)
                        No change in performance detected.

?PO 1414214 triples/4.1 (?, type, person) triple IDs
                        time:   [118.90 ms 118.90 ms 118.91 ms]
                        change: [+0.7300% +1.0019% +1.2754%] (p = 0.08 > 0.05)
                        No change in performance detected.
?PO 1414214 triples/4.2 (?, type, person) str subjects
                        time:   [313.29 ms 313.74 ms 313.86 ms]
                        change: [+0.3570% +0.8375% +1.3217%] (p = 0.12 > 0.05)
                        No change in performance detected.
?PO 1414214 triples/4.3 (?, type, person) str triples
                        time:   [338.70 ms 338.86 ms 339.47 ms]
                        change: [+4.6851% +4.8734% +5.0619%] (p = 0.10 > 0.05)
                        No change in performance detected.
?PO 1414214 triples/4.4 (?, type, person) Sophia triples
                        time:   [360.62 ms 360.67 ms 360.68 ms]
                        change: [-0.8126% +0.0232% +0.8730%] (p = 0.82 > 0.05)
                        No change in performance detected.
```

**Comment by KonradHoeffner** [comment]
# Benchmarking ??? pattern (all triples) on i9-10900k

## Before

```
Benchmarking ??? (all)/0.1 all triple IDs: Warming up for 3.0000 s
??? (all)/0.1 all triple IDs
                        time:   [1.6171 s 1.6180 s 1.6189 s]
??? (all)/0.2 all str triples
                        time:   [6.3724 s 6.3750 s 6.3785 s]
??? (all)/0.3 all Sophia triples
                        time:   [7.8375 s 7.8492 s 7.8624 s]
```

### After

```
??? (all)/0.1 all triple IDs
                        time:   [1.6182 s 1.6336 s 1.6480 s]
                        change: [+0.1297% +0.9638% +1.8168%] (p = 0.07 > 0.05)
                        No change in performance detected.
??? (all)/0.2 all str triples
                        time:   [7.1611 s 7.2483 s 7.3353 s]
                        change: [+12.424% +13.699% +14.932%] (p = 0.00 < 0.05)
                        Performance has regressed.
??? (all)/0.3 all Sophia triples
                        time:   [8.5335 s 8.5736 s 8.6102 s]
                        change: [+8.7127% +9.2289% +9.6978%] (p = 0.00 < 0.05)
                        Performance has regressed.
```

**Comment by KonradHoeffner** [comment]
Maybe the idx variable needs to be updated in the else part of the get_x_string function?

**Comment by KonradHoeffner** [comment]
```
    fn get_x_string(&mut self, i: usize, pos: usize, kind: &'static IdKind) -> Result<Arc<str>, DictErr> {
        debug_assert!(i != 0);
        if self.idx[pos] == i {
            Ok(self.arc[pos].as_ref().unwrap().clone())
        } else {
            let ret: Arc<str> = self.hdt.dict.id_to_string(i, kind)?.into();
            self.arc[pos] = Some(ret.clone());
+          self.idx[pos] = i;
            Ok(ret)
        }
```

```
??? (all)/0.1 all triple IDs
                        time:   [1.6308 s 1.6329 s 1.6366 s]
                        change: [+0.7702% +0.9257% +1.1700%] (p = 0.00 < 0.05)
                        Change within noise threshold.
??? (all)/0.2 all str triples
                        time:   [5.8885 s 5.8956 s 5.9026 s]
                        change: [-7.6339% -7.5201% -7.3964%] (p = 0.00 < 0.05)
                        Performance has improved.
??? (all)/0.3 all Sophia triples
                        time:   [6.9292 s 6.9454 s 6.9653 s]
                        change: [-11.755% -11.514% -11.252%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Comment by pchampin** [comment]
> Maybe the idx variable needs to be updated in the else part of the get_x_string function?

Duh! So silly of me... :facepalm: Thanks for fixing this.

**Comment by KonradHoeffner** [comment]
# Cases

After benchmarking and thinking about this there seem to be the following cases:

1. triple pattern with three constants SPO: this is just an ask query, so performance shouldn't differ much regardless of implementation
2. triple patterns with two constants and one variable, SP?, S?O, ?PO: Arc won't do anything because the variable never has the same value twice and the constants we just want to return from the parameters but MownStr is perfect here. This case is my biggest worry because they queries can take a long time to execute and I don't like losing 10% performance because of Arc over MownStr.
3. triple patterns with one constant and two adjacent variables S?? ??O: there is one constant which we want to pass back, one variable which is easy to deduplicate (P in S?? and S in ??O), and one variable which is hard to deduplicate.
4. triple pattern with one constant and two disjointed variables ?P?: there is one constant that we want to pass back and two hard to deduplicate variables.
5. triple pattern with 3 variables ???, which is the best case for Arc but I think not used that often, and is equivalent to the triples() method.

## Ideas for Solutions (numbers unrelated)

1. Use Arc as is: Just take the tradeoff with worse performance in some cases for benefits in others.
2. Keep it with MownStr and keep the good performance on two variable queries but lose the potential benefits in the other cases (especially the two variables cases need to be deduplicated and benchmarked)
3. Return normal references instead of Arc along with some kind of String pool. However this is hard to implement because the borrow checker of Rust does not allow returning references with lifetimes relating to something in the same struct.
4. Create a new MownStr variant but when it gets cloned, instead of cloning the Box<str>, which is slow, it creates a reference to the box.
5. Try Rc instead of Arc. But that may harm applications with multithreading.
6. Don't try optimizing it and instead tell users to use specific methods instead for each case when performance is an issue. This is feasible for Hdt but not for the Sophia Hdt Graph.

I favor solution 4 but I'm not sure if that's possible with Rust and as second favorite solution 3, but that may be difficult to do as well.

**Comment by KonradHoeffner** [comment]
I just forked your MownStr repository because I wanted to change `clone()` so that always returns a borrowed MownStr but I found the `borrowed` method. Won't that solve our use case without needing Arc?

**Comment by KonradHoeffner** [comment]
Unfortunately, borrowed returns MownStr instead of Mownstr<'a> so it can't be returned but I successfully changed added the lifetime to a local copy of MownStr. Is this feasible to add or will this break something?

**Comment by pchampin** [comment]
> Is this feasible to add or will this break something?

It will break something. Consider the following code (assuming that `borrowed` returns `MownStr<'a>`:
```rust
    let m1: MownStr<'static>;
    {
        let m2: MownStr<'static> = "hello world".to_string().into();
        m1 = m2.borrowed();
        println!("{}", m1);
    }
    println!("{}", m1);
```
It would compile, but the second `println!` would print garbage, because the text owned by `m2` and borrowed by `m1` is unallocated at the curly bracket...

**Comment by KonradHoeffner** [comment]
Enabling the triple cache for all patterns with at two variables gave a massive boost (down to 69%) to the tested ??O query:

  | o | o - load | / mownstr
-- | -- | -- | --
mownstr  | 34930677 | 9358164 | 1
rc  | 35477675 | 9905162 | 1.058451423
arc  | 35528558 | 9956045 | 1.063888707
cached arc  | 31998853 | 6426340 | 0.686709487
  |   | rc / arc | 0.9948892356

**Pull request merged**
